### ISSUE TITLE
Difference between pak and pkgr

### ISSUE THREAD

**Issue by mattfidler** [metrumresearchgroup/pkgr#222] opened 2020-01-20 14:49 UTC
Nice job on the package tool.

I asked this question at ACoP and was told to reach out to you. (I'm a bit behind)  

What is the difference between Rstudio's solution:

https://github.com/r-lib/pak

And this solution?

Does it support more repositories?  Is it taking from some frozen package (it doesn't download from CRAN)?  Is it simply having a yaml header that makes reproducible of a package easy?  Does it support importing a session info?

**Comment by dpastoor** [comment] 2020-01-20 16:11
Good question, probably need to cover this in the readme in more depth. The answer is that pkgr philosophically comes from a very different approach (will get to below), and overall does both less and more.

Before all, pkgr is a single, couple meg binary that has 0 dependencies, which means that whether you're dropping it into a locked down hpc, your windows laptop, or a docker container, "installation" is instant. In fact, you can also even have multiple alias'd pkgr's side-by-side in case of versioning needs over time. Since its in go, it can talk to all installs of R on a system at once as well.

pak needs ~ 30+ r packages, to bootstrap itself, and those must be installed for each version of R, and risk breaking as system deps change (though reasonably that chance is small since the are mostly just c code (processx, ps, etc). Thats what it took to get the event loop/parallel installs but that is IMO a high burden, especially for validated/constrained environments to manage.

Now, onto functionality:

First, pkgr is really focused on declarative state of the environment. You specify in a configuration exactly how your environment should look, and pkgr will figure out how to get you there with a minimum of work.

This obviously is very different than how pak/install.packages works by imperatively stating the work to be done, and interactively guiding you to what you might want (for example now pak has a number of dialogs I believe when it detects out of date pkgs etc that you then pick what you want to do interactively).

By making the state of your system declarative, this facilitates reproducibility as someone else using the same pkgr.yml file should get to the "same" place, at least on a similar system.

One side effect of needing to be declarative is some things that used to be necessary to do in multiple pak/install.packages calls must be surfaced in the config file. 

For example, how might you only install the suggested packages for _some_ packages, but not others. Well in pak/install.packages, you'd use multiple calls, and change the dependencies argument. Similarly, how do you tell it to install a package from a _particular_ repo, even if that package is available in repos earlier in the order of getOption("repos"). This is where customizations allow you to declaratively express that.

This also has the added side effect of us being able to communicate those actions since this was a design decision from day 1, in the fashion of `pkgr plan`. plan will tell you all you need around the package versions, types, what repo they'd come from before actually doing any work. I believe pak has been exploring the concept of a dry-run, but that still wouldn't solve if you really wanted to know what would happen in the case you'd need multiple pak calls.

Now, where pak and pkgr become aligned is that they both do everything in parallel, figuring out the proper order to install packages in, and doing some maneuvering of how packages get installed (for example a binary package is installed by first installing the binary to a tmp dir, then installing it into the goal folder, that prevents issues with deleting the working package then erroring during install. pkgr goes one step further though, and actually snapshots your environment and on a failed install will _rollback_ the state to the previous working env, vs pak will leave you with a partially installed state.

Finally, where pak and pkgr begin to significantly deviate is in the scope of functionality they support. pak can install from _way_ more locations. github/gitlab/remote git repos etc. pkgr constrains itself to just cran-like repos  (local or remote) and (soon) individual pkg tarballs. This purposefully forces on the upstream some additional reproducibility constraints. I've watched people too often build custom/subtly broken environments by overlaying remotes::install_github commands in a way that gets out of sync dep versions, especially for packages like rlang. We "make" you build cran-like repos that somewhat force some time to be taken to think around the environment being constructed.

As such, I don't really see pkgr as a one-size-fits-all tool, at least as it currently exists. Rather it is focused on the R package consumer getting to a reproducible environment as quickly and clearly as possible. Its not really great as a 'developer' tool when you to experiment or try out tip versions of repos. I would like to get there one day, but for our purposes, thats what MPN is for as an immutable external repo to install all you, as a scientist, need for day-to-day production work that pkgr can consume.

Let me know if I can clarify any of these points further!

**Comment by mattfidler** [comment] 2020-01-21 17:36
One point -- dose pkgr use `MPN` (I'm assuming metrum cran or perhaps the microsoft CRAN snapshot) by default?  I was wondering this because some of the metrum package download counts have dropped off.

**Comment by mattfidler** [comment] 2020-01-21 17:37
Otherwise, it may be useful to update the `README` to help others.  Also change `pakrat` to `renv`

**Comment by dpastoor** [comment] 2020-03-01 02:32
Following up - pkgr does not use anything by by default, however we ourselves are now moving towards pulling everything from MPN, plus we have started to offer a professional support service around MPN so for clients that subscribe helping them migrate to that, so download numbers could very much be skewing downward.

updating readme with link to this issue around the differences with pak

**Closed** 2020-03-03 03:45 UTC
